2021-11-12 14:50:20 [INFO] 加法P0开始运行测试 (test_calculator.py:28)
2021-11-12 14:50:20 [INFO] 数据[1, 1, 2] (test_calculator.py:29)
2021-11-12 14:50:20 [INFO] 加法P0开始运行测试 (test_calculator.py:28)
2021-11-12 14:50:20 [INFO] 数据[-0.01, 0.02, 0.01] (test_calculator.py:29)
2021-11-12 14:50:20 [INFO] 加法P0开始运行测试 (test_calculator.py:28)
2021-11-12 14:50:20 [INFO] 数据[10, 0.02, 10.02] (test_calculator.py:29)
2021-11-12 14:50:20 [INFO] 加法P1_1开始运行测试 (test_calculator.py:35)
2021-11-12 14:50:20 [INFO] 数据[98.99, 99, 197.99] (test_calculator.py:36)
2021-11-12 14:50:20 [INFO] 加法P1_1开始运行测试 (test_calculator.py:35)
2021-11-12 14:50:20 [INFO] 数据[99, 98.99, 197.99] (test_calculator.py:36)
2021-11-12 14:50:20 [INFO] 加法P1_1开始运行测试 (test_calculator.py:35)
2021-11-12 14:50:20 [INFO] 数据[-98.99, -99, -197.99] (test_calculator.py:36)
2021-11-12 14:50:20 [INFO] 加法P1_1开始运行测试 (test_calculator.py:35)
2021-11-12 14:50:20 [INFO] 数据[-99, -98.99, -197.99] (test_calculator.py:36)
2021-11-12 14:50:20 [INFO] 加法P1_1开始运行测试 (test_calculator.py:35)
2021-11-12 14:50:20 [INFO] 数据[99.01, 0, '参数大小超出范围'] (test_calculator.py:36)
2021-11-12 14:50:20 [INFO] 加法P1_1开始运行测试 (test_calculator.py:35)
2021-11-12 14:50:20 [INFO] 数据[-99.01, -1, '参数大小超出范围'] (test_calculator.py:36)
2021-11-12 14:50:20 [INFO] 加法P1_1开始运行测试 (test_calculator.py:35)
2021-11-12 14:50:20 [INFO] 数据[2, 99.01, '参数大小超出范围'] (test_calculator.py:36)
2021-11-12 14:50:20 [INFO] 加法P1_1开始运行测试 (test_calculator.py:35)
2021-11-12 14:50:20 [INFO] 数据[1, -99.01, '参数大小超出范围'] (test_calculator.py:36)
2021-11-12 14:50:20 [INFO] 加法P1_2开始运行测试 (test_calculator.py:42)
2021-11-12 14:50:20 [INFO] 数据['文', 9.3, 'TypeError'] (test_calculator.py:43)
2021-11-12 14:50:20 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:45)
2021-11-12 14:50:20 [INFO] 加法P1_2开始运行测试 (test_calculator.py:42)
2021-11-12 14:50:20 [INFO] 数据[4, '字', 'TypeError'] (test_calculator.py:43)
2021-11-12 14:50:20 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:45)
2021-11-12 14:50:20 [INFO] 加法P1_2开始运行测试 (test_calculator.py:42)
2021-11-12 14:50:20 [INFO] 数据['nu', 0.2, 'TypeError'] (test_calculator.py:43)
2021-11-12 14:50:20 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:45)
2021-11-12 14:50:20 [INFO] 加法P1_2开始运行测试 (test_calculator.py:42)
2021-11-12 14:50:20 [INFO] 数据[30, 't', 'TypeError'] (test_calculator.py:43)
2021-11-12 14:50:20 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:45)
2021-11-12 14:50:20 [INFO] 加法P1_2开始运行测试 (test_calculator.py:42)
2021-11-12 14:50:20 [INFO] 数据['*&', 0.2, 'TypeError'] (test_calculator.py:43)
2021-11-12 14:50:20 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:45)
2021-11-12 14:50:20 [INFO] 加法P1_2开始运行测试 (test_calculator.py:42)
2021-11-12 14:50:20 [INFO] 数据[21.45, '@', 'TypeError'] (test_calculator.py:43)
2021-11-12 14:50:20 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:45)
2021-11-12 14:50:20 [INFO] 加法P2开始运行测试 (test_calculator.py:52)
2021-11-12 14:50:20 [INFO] 数据['None', 20.93, 'TypeError'] (test_calculator.py:53)
2021-11-12 14:50:20 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:55)
2021-11-12 14:50:20 [INFO] 加法P2开始运行测试 (test_calculator.py:52)
2021-11-12 14:50:20 [INFO] 数据[-3, 'None', 'TypeError'] (test_calculator.py:53)
2021-11-12 14:50:20 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:55)
2021-11-12 14:50:20 [INFO] 加法P2开始运行测试 (test_calculator.py:52)
2021-11-12 14:50:20 [INFO] 数据[' ', 3.14, 'TypeError'] (test_calculator.py:53)
2021-11-12 14:50:20 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:55)
2021-11-12 14:50:20 [INFO] 加法P2开始运行测试 (test_calculator.py:52)
2021-11-12 14:50:20 [INFO] 数据[-90, ' ', 'TypeError'] (test_calculator.py:53)
2021-11-12 14:50:20 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:55)
2021-11-12 14:50:20 [INFO] 除法P0开始运行测试 (test_calculator.py:64)
2021-11-12 14:50:20 [INFO] 数据[1, 1, 1] (test_calculator.py:65)
2021-11-12 14:50:20 [INFO] 除法P0开始运行测试 (test_calculator.py:64)
2021-11-12 14:50:20 [INFO] 数据[-0.01, -0.02, 0.5] (test_calculator.py:65)
2021-11-12 14:50:20 [INFO] 除法P0开始运行测试 (test_calculator.py:64)
2021-11-12 14:50:20 [INFO] 数据[-0.01, 0.02, -0.5] (test_calculator.py:65)
2021-11-12 14:50:21 [INFO] 除法P0开始运行测试 (test_calculator.py:64)
2021-11-12 14:50:21 [INFO] 数据[10, 0.02, 500] (test_calculator.py:65)
2021-11-12 14:50:21 [INFO] 除法P1_1开始运行测试 (test_calculator.py:71)
2021-11-12 14:50:21 [INFO] 数据[99, 0, 'ZeroDivisionError'] (test_calculator.py:72)
2021-11-12 14:50:21 [INFO] 除法P1_1开始运行测试 (test_calculator.py:71)
2021-11-12 14:50:21 [INFO] 数据['文', 9.3, 'TypeError'] (test_calculator.py:72)
2021-11-12 14:50:21 [INFO] 除法P1_1开始运行测试 (test_calculator.py:71)
2021-11-12 14:50:21 [INFO] 数据[4, '字', 'TypeError'] (test_calculator.py:72)
2021-11-12 14:50:21 [INFO] 除法P1_1开始运行测试 (test_calculator.py:71)
2021-11-12 14:50:21 [INFO] 数据['nu', 0.2, 'TypeError'] (test_calculator.py:72)
2021-11-12 14:50:21 [INFO] 除法P1_1开始运行测试 (test_calculator.py:71)
2021-11-12 14:50:21 [INFO] 数据[30, 't', 'TypeError'] (test_calculator.py:72)
2021-11-12 14:50:21 [INFO] 除法P1_1开始运行测试 (test_calculator.py:71)
2021-11-12 14:50:21 [INFO] 数据['*&', 0.2, 'TypeError'] (test_calculator.py:72)
2021-11-12 14:50:21 [INFO] 除法P1_1开始运行测试 (test_calculator.py:71)
2021-11-12 14:50:21 [INFO] 数据[21.45, '@', 'TypeError'] (test_calculator.py:72)
2021-11-12 14:50:21 [INFO] 除法P2开始运行测试 (test_calculator.py:80)
2021-11-12 14:50:21 [INFO] 数据['None', 20.93, 'TypeError'] (test_calculator.py:81)
2021-11-12 14:50:21 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:83)
2021-11-12 14:50:21 [INFO] 除法P2开始运行测试 (test_calculator.py:80)
2021-11-12 14:50:21 [INFO] 数据[-3, 'None', 'TypeError'] (test_calculator.py:81)
2021-11-12 14:50:21 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:83)
2021-11-12 14:50:21 [INFO] 除法P2开始运行测试 (test_calculator.py:80)
2021-11-12 14:50:21 [INFO] 数据[' ', 3.14, 'TypeError'] (test_calculator.py:81)
2021-11-12 14:50:21 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:83)
2021-11-12 14:50:21 [INFO] 除法P2开始运行测试 (test_calculator.py:80)
2021-11-12 14:50:21 [INFO] 数据[-90, ' ', 'TypeError'] (test_calculator.py:81)
2021-11-12 14:50:21 [INFO] 异常<ExceptionInfo for raises contextmanager> (test_calculator.py:83)
