[32mINFO    [0m root:test_calculator.py:42 加法P1_2开始运行测试
[32mINFO    [0m root:test_calculator.py:43 数据['文', 9.3, 'TypeError']
[32mINFO    [0m root:test_calculator.py:45 异常<ExceptionInfo for raises contextmanager>